# Generated by Django 5.0 on 2024-07-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_content0_alter_blogpost_content1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='post_id',
            new_name='id',
        ),
    ]
