# Generated by Django 5.0 on 2024-07-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_post_id_blogpost_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='id',
            new_name='post_id',
        ),
    ]
