# Generated by Django 5.0 on 2024-07-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_id_blogpost_post_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
